print("Hello, World!")
print("Learn pull requests")
print("Start working from a new branch")
print("Hello, Vita")
print("Hope, we can do our first pull request")
print("If not, ")
print("We'll try again...")
print("...and again")
print(":)")
